"""ns-3 (IEEE 802.11p) VANET backend.

Runs the ``ns3/vanet-beacon.cc`` scenario over the SUMO/IDM vehicle trajectories
and turns the real beacon-reception trace into the same
:class:`~src.vanet.partial_obs.PartialObservation` the analytic backend produces.

A beacon generated by vehicle *v* at time *g* is considered **collected** by the
traffic-management system if it is received by at least one other equipped
vehicle (V2V backhaul assumed); realised PDR / latency / AoI then emerge from
the ns-3 PHY + MAC + mobility rather than being configured.

If ns-3 is not built / not found, :class:`Ns3Unavailable` is raised and callers
fall back to the analytic channel.
"""
from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path

import numpy as np

from .channel import Beacon
from .partial_obs import assemble_partial_obs
from .mobility_export import export_ns2_mobility, vehicle_state_at


class Ns3Unavailable(RuntimeError):
    pass


def ns3_dir(cfg) -> Path | None:
    cand = []
    c = cfg.get("vanet", {}).get("ns3", {}).get("ns3_dir")
    if c:
        cand.append(Path(c))
    if os.environ.get("NS3_DIR"):
        cand.append(Path(os.environ["NS3_DIR"]))
    cand.append(Path(cfg["_meta"]["repo_root"]) / "ns-3-dev")
    for d in cand:
        if d and (d / "ns3").exists():
            return d
    return None


def ns3_available(cfg) -> bool:
    return ns3_dir(cfg) is not None


# --------------------------------------------------------------------------- #
def run_ns3(sim_out, cfg, penetration: float, seed: int, logger=None):
    d = ns3_dir(cfg)
    if d is None:
        raise Ns3Unavailable("ns-3 not found (set $NS3_DIR or run ns3/setup_ns3.sh)")
    ns = cfg["vanet"].get("ns3", {})
    work = Path(cfg["_meta"]["repo_root"]) / "data" / "vanet"
    work.mkdir(parents=True, exist_ok=True)
    tag = f"{sim_out.corridor_id}_{sim_out.demand_level}_p{int(penetration*100)}_s{seed}"
    mob = export_ns2_mobility(sim_out, work / f"mobility_{tag}.tcl", penetration, seed)
    rx_csv = work / f"reception_{tag}.csv"

    args = (f"vanet-beacon --mobility={mob.path} --nNodes={mob.n_nodes} "
            f"--duration={sim_out.times[-1] if len(sim_out.times) else 60:.0f} "
            f"--beaconHz={float(ns.get('beacon_hz', 10))} "
            f"--pktBytes={int(ns.get('packet_bytes', 200))} "
            f"--txPowerDbm={float(ns.get('tx_power_dbm', 20))} "
            f"--phyMode={ns.get('phy_mode', 'OfdmRate6MbpsBW10MHz')} "
            f"--propagation={ns.get('propagation', 'LogDistance')} "
            f"--rxTrace={rx_csv} --seed={seed}")
    if logger:
        logger.info(f"  ns-3: {mob.n_nodes} equipped nodes  ->  ./ns3 run \"{args[:90]}...\"")
    t0 = time.time()
    proc = subprocess.run([str(d / "ns3"), "run", args], cwd=str(d),
                          capture_output=True, text=True,
                          timeout=int(ns.get("timeout_s", 2400)))
    if proc.returncode != 0 or not rx_csv.exists():
        raise Ns3Unavailable(
            f"ns-3 run failed (rc={proc.returncode}). "
            f"stderr tail:\n{proc.stderr[-800:]}")
    if logger:
        logger.info(f"  ns-3 finished in {time.time()-t0:.0f}s  -> {rx_csv.name}")
    return _parse_trace(rx_csv), mob


def _parse_trace(csv_path: Path):
    import pandas as pd
    df = pd.read_csv(csv_path)
    df = df[df["event"].isin(["tx", "rx"])].copy()
    for c in ("t", "gen_t", "dist_m"):
        df[c] = pd.to_numeric(df[c], errors="coerce")
    for c in ("node", "peer"):
        df[c] = pd.to_numeric(df[c], errors="coerce").astype("Int64")
    return df


# --------------------------------------------------------------------------- #
def build_partial_observation_ns3(sim_out, cfg, penetration: float, seed: int,
                                  logger=None):
    df, mob = run_ns3(sim_out, cfg, penetration, seed, logger)
    tx = df[df["event"] == "tx"]
    rx = df[df["event"] == "rx"].dropna(subset=["peer", "gen_t"])
    n_tx = int(len(tx))

    # first reception per (tx-vehicle, generation-time) == "collected" event
    beacons: list[Beacon] = []
    latencies = []
    if len(rx):
        rx = rx.assign(_key=rx["peer"].astype(int).astype(str) + "_" +
                       rx["gen_t"].round(3).astype(str))
        first = rx.sort_values("t").groupby("_key", as_index=False).first()
        for _, r in first.iterrows():
            node_idx = int(r["peer"])
            vid = mob.node_to_veh.get(node_idx)
            if vid is None:
                continue
            st = vehicle_state_at(sim_out, vid, float(r["gen_t"]))
            if st is None:
                continue
            cell, spd, xm = st
            beacons.append(Beacon(veh_id=vid, cell=cell, x_m=xm, speed_mps=spd,
                                  accel_mps2=0.0, heading_deg=sim_out.heading_deg,
                                  gen_time_s=float(r["gen_t"]),
                                  arrival_time_s=float(r["t"])))
            latencies.append(float(r["t"]) - float(r["gen_t"]))

    realized_pdr = round(len(beacons) / n_tx, 4) if n_tx else 0.0
    mean_lat_ms = round(float(np.mean(latencies)) * 1000.0, 2) if latencies else 0.0
    if logger:
        logger.info(f"  ns-3 realised: PDR={realized_pdr}  mean latency={mean_lat_ms} ms  "
                    f"collected BSMs={len(beacons)}/{n_tx}")

    po = assemble_partial_obs(
        beacons, sim_out, cfg, penetration=penetration, pdr=realized_pdr,
        latency_ms=mean_lat_ms, backend="ns3",
        extra_delivery_stats={"beacons_sent": n_tx, "beacons_delivered": len(beacons),
                              "realized_pdr": realized_pdr,
                              "realized_mean_latency_ms": mean_lat_ms,
                              "ns3_rx_events": int(len(rx)),
                              "equipped_nodes": mob.n_nodes})
    return po
